// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    CustomizeDialogForm: typeof import('./src/components/customize/CustomizeDialogForm.vue')['default']
    CustomizeForm: typeof import('./src/components/customize/CustomizeForm.vue')['default']
    CustomizePage: typeof import('./src/components/customize/CustomizePage.vue')['default']
    CustomizePagination: typeof import('./src/components/customize/CustomizePagination.vue')['default']
    CustomizeSwitch: typeof import('./src/components/customize/CustomizeSwitch.vue')['default']
    CustomizeTable: typeof import('./src/components/customize/CustomizeTable.vue')['default']
    EditableList: typeof import('./src/components/EditableList.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
  }
}

export { }
