// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    CodeMirrorDialog: typeof import('./src/components/CodeMirrorDialog.vue')['default']
    EditableList: typeof import('./src/components/EditableList.vue')['default']
    ResponseTextDialog: typeof import('./src/components/ResponseTextDialog.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
  }
}

export { }
