export const DefaultSetting = () => ({
  openSave: false,
  openMock: false,
  openUrl: '127.0.0.1:8888',
  tag: '',
  limit: null,
  checkParams: true,
  checkBody: true,
  openUrlList: ['127.0.0.1:8888'],
  tagList: [],
  removeRequestUrlParams: [],
  removeRequestBodyParams: ['t'],
  listUrlRemoveStr: [],
  filterUrl: [],
});
